### ISSUE TITLE
Postscript output is broken when certain URLs are in input file

### ISSUE THREAD

**Issue by ThePotatoArchivist** [HouseHouseHouseHouseHouseHouse/intuitive-arrangement#2]
The PostScript doesn't show output when the input file contains certain URLs. The document display or converter hangs.

This probably isn't directly linked to URLs, but I first noticed this when I tried to convert a file with URLs. 

## Steps to reproduce
1. Create a file with the following content:
```
www.curseforge.com/minecraft/mc-mods/alloygery
```
2. Generate postscript output
3. Open output file or convert to pdf

**Comment by j12bates** [comment]
known issue, this is because the PostScript code can't truncate single words that won't fit on a line (it adds words until they don't fit and then moves on to the next line with the remaining words, so it just loops); I had it as a TODO for a while and I'll get around to fixing it eventually

**Comment by j12bates** [comment]
yay I finally got around to fixing it
