### ISSUE TITLE
[Feature Request] Integration Features

### ISSUE THREAD

**Issue by ThePotatoArchivist** [HouseHouseHouseHouseHouseHouse/intuitive-arrangement#4]
Miscellaneous ideas to make it more of an integrated command-line tool. These are all only suggestions; do the ones you want to do

- Makefile or `sh` script to install to `/opt` or `/usr/local/share` and symlink `generate.rb` to `/usr/local/bin/intuitype` (Makefiles seem to be more standard but I don't know if you know or want to learn Makefile)
- Can also use stylesheets in `.intuitype` or `.config/intuitype` in addition to `src/res` (in a similar manner to `$PATH`)
- Flag to use any file as stylesheet
- `--pdf` flag to filter through `ps2pdf` if installed, wrapper `.sh` script needed?
- `-o` flag for output file

**Comment by j12bates** [comment]
I'm making a wrapper script to take command-line options and output to PDF instead of PS since the PS doesn't really make sense at all

Reminder to self to figure out embedding fonts into output PDF with ghostscript and just research what command-line options to use

**Comment by j12bates** [comment]
Added a makefile with install target, Wrapper file for invocation, output is always PDF since the PS is really just for processing and doesn't work nicely with most viewers

and btw I finally fixed that one issue with Symbol characters not showing up
